[tool.poetry]
name = "plexdl"
version = "0.3.2"
description = ""
authors = ["Daniel Hoherd <daniel.hoherd@gmail.com>"]
license = "MIT License"
classifiers=[
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Topic :: Utilities",
]

[tool.poetry.scripts]
plexdl = 'plexdl.cli:main'

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.0.3"
PlexAPI = "^4.8.0"
humanfriendly = "^10.0"
requests = "^2.26.0"
importlib-metadata = "^4.8.2"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
tox = "^3.20.1"
pytest = "^6.1.1"

[tool.black]
line-length = 132

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py39
skipsdist = True

[testenv]
whitelist_externals = poetry
#skip_install = true
deps = pre-commit
commands =
    pre-commit install -f --install-hooks
    pre-commit run --all-files
    poetry install -vvv
    poetry run pytest tests/

[pep8]
ignore = E265
"""
[build-system]
requires = ["poetry>=1.1.4"]
build-backend = "poetry.masonry.api"
