"""Install plexdl."""
# -*- coding: utf-8 -*-
# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

setup(
    long_description=open("README.md").read(),
    name="plexdl",
    version="0.1.0",
    python_requires="==3.*,>=3.7.0",
    author="Daniel Hoherd",
    author_email="daniel.hoherd@gmail.com",
    license="UNLICENSE",
    packages=["plexdl"],
    package_data={},
    install_requires=["click==7.*,>=7.0.0", "plexapi==3.*,>=3.2.0"],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Environment :: Console",
        "License :: OSI Approved :: UNLICENSE License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Topic :: Utilities",
    ],
    extras_require={
        "dev": [
            "black==19.*,>=19.10.0",
            "bpython==0.*,>=0.18.0",
            "dephell==0.*,>=0.7.8",
            "fissix==19.*,>=19.2.0",
            "flake8==3.*,>=3.7.9",
        ]
    },
)
